spring:
  application:
    name: member
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888

  jpa:
    database: mysql
    show-sql: on
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/web
    username: web
    password: web
