server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gegurakzi/Tag_Manager_Server
          searchPaths: config
          default-label: main