server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gegurakzi/Spring_Cloud_Basics
          searchPaths: config
          default-label: feature/malachai/user-service-init